let custType=[
    {
        id:1,
        name:'品牌商',
        appId:[1],
        useType:[1],
        userType:5
    },
    {
        id:2,
        name:'通讯运营商',
        appId:[1],
        useType:[2],
        userType:1
    },
    {
        id:3,
        name:'沃管车代理商',
        appId:[1],
        useType:[],
        userType:2
    },
    {
        id:4,
        name:'政企用户',
        appId:[2],
        useType:[2,3],
        userType:8
    },
    {
        id:5,
        name:'品牌代理商',
        appId:[1],
        useType:[1,5],
        userType:2
    },
    {
        id:6,
        name:'服务运营商',
        appId:[],
        useType:[],
        userType:1
    },
    {
        id:7,
        name:'私家车主',
        appId:[],
        useType:[],
        userType:7
    }
];

export default DATA=[
    {
        name:'cust_type',
        data:custType
    }
];
